targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for all json_serializable builders
          explicit_to_json: true
          include_if_null: false
      freezed:
        options:
          # Options for freezed code generation
          copy_with: true
      freezed|freezed:
        generate_for:
          include:
            - lib/data/models/**/*.dart
        options:
          # Disable invalid_annotation_target warning
          ignore_for_file:
            - invalid_annotation_target
